// Color+Evapotrack.swift
// Evapotrack
//
// Type-safe access to the Evapotrack color palette.
// All colors defined in Assets.xcassets with light and dark variants.

import SwiftUI

extension Color {

    // MARK: - Semantic Aliases
    // Base palette tokens (evPrimaryBlue, evDeepNavy, etc.) are
    // auto-generated by Xcode from the Asset Catalog color sets.

    static let evPrimaryText: Color = .evInkBlack
    static let evSecondaryText: Color = .evSlateGray
    static let evBackground: Color = .evSoftGray1
    static let evBorder: Color = .evSoftGray2
    static let evIcon: Color = .evDeepNavy
    static let evIconInactive: Color = .evSlateGray
    static let evButtonPrimary: Color = .evPrimaryBlue
    static let evButtonDisabled: Color = .evCoolMist
    static let evHighlight: Color = .evFrostBlue
}
