// © 2026 Evapotrack. All rights reserved.
// Color+Evapotrack.swift
// Evapotrack
//
// Type-safe access to the Evapotrack color palette.
// All colors defined in Assets.xcassets with light and dark variants.

import SwiftUI

extension Color {

    // MARK: - Semantic Aliases
    // Base palette tokens (evPrimaryBlue, evDeepNavy, etc.) are
    // auto-generated by Xcode from the Asset Catalog color sets.

    static let evPrimaryText: Color = .evInkBlack
    static let evSecondaryText: Color = .evSlateGray
    static let evBackground: Color = .evSoftGray1
    static let evBorder: Color = .evSoftGray2
    static let evIcon: Color = .evDeepNavy
    static let evIconInactive: Color = .evSlateGray
    static let evButtonPrimary: Color = .evPrimaryBlue
    static let evButtonDisabled: Color = .evCoolMist
    static let evHighlight: Color = .evFrostBlue

    // MARK: - Chart Overlay Colors

    static let evWarmOrange = Color(red: 0.92, green: 0.55, blue: 0.20)
    static let evSoftPurple = Color(red: 0.58, green: 0.40, blue: 0.82)
}
